name: "Podcast Generator Linkedin Course"
author: "KiwiUsr"
description: "Generates a feed for a podcast (Linkedin Learning Course) for a yaml file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "green"
inputs:
  email:
    description: The commiter's email adress
    required: true
    default: ${{github.actor}}@localhost

  name:
    description: The commiter's name
    required: true
    default: ${{github.actor}}@localhost
